"""level column add in Word table

Revision ID: be8b7c73dd09
Revises: 4635c491b3e4
Create Date: 2020-08-23 23:40:39.617984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8b7c73dd09'
down_revision = '4635c491b3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'level')
    # ### end Alembic commands ###
