"""empty message

Revision ID: c723b1b25ab6
Revises: 7ccd63bf1261
Create Date: 2020-08-01 17:47:04.481824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c723b1b25ab6'
down_revision = '7ccd63bf1261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'language', type_='foreignkey')
    op.drop_column('language', 'user_id')
    op.add_column('user', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'language', ['language_id'], ['id'])
    op.add_column('word', sa.Column('dictionary_id', sa.Integer(), nullable=True))
    op.add_column('word', sa.Column('foreign_language', sa.String(length=128), nullable=True))
    op.add_column('word', sa.Column('native_language', sa.String(length=128), nullable=True))
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.create_foreign_key(None, 'word', 'dictionary', ['dictionary_id'], ['id'])
    op.drop_column('word', 'english')
    op.drop_column('word', 'user_id')
    op.drop_column('word', 'russian')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('russian', sa.VARCHAR(length=128), nullable=True))
    op.add_column('word', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('word', sa.Column('english', sa.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.create_foreign_key(None, 'word', 'user', ['user_id'], ['id'])
    op.drop_column('word', 'native_language')
    op.drop_column('word', 'foreign_language')
    op.drop_column('word', 'dictionary_id')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'language_id')
    op.add_column('language', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'language', 'user', ['user_id'], ['id'])
    op.drop_table('dictionary')
    # ### end Alembic commands ###
